/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.td.tafd.licensevalidation;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author mb255051
 */
public class LicenseDetailsView extends JPanel {
    
    private JLabel userIdLabel;
	private JLabel userId;
	
	private JLabel userEmailLabel;
	private JLabel userEmail;
	
	private JLabel licenseExpiryDateLabel;
	private JLabel licenseExpiryDate;
	
	private JLabel licenseCreationDateLabel;
	private JLabel licenseCreationDate;
	
	private JLabel licenseModificationDateLabel;
	private JLabel licenseModificationDate;
	
	private JLabel maxUsersLabel;
	private JLabel maxUsers;
	
	private JLabel maxSourcesLabel;
	private JLabel maxSources;
	
	private JLabel supportedDbsLabel;
	private JLabel supportedDbs;
	
	private JLabel supportedTmaVersionLabel;
	private JLabel supportedTmaVersion;
	
	private JLabel supportedTmaModulesLabel;
	private JLabel supportedTmaModules;

    /**
     * Creates new form LicenseDetailsView
     */
    public LicenseDetailsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
